= Playground
:source-highlighter: highlight.js
:toc:
:toclevels: 5

This is mailto:reinhard.griech@endress.com[Hardy's, Playground on egit] personal playground.
But everyone is free to contribute.

Mirror of the repo can be found at https://github.com/rgrr/playground[github].


== Playground

* link:cpp[C/C++]
* link:rp2040[RP2040 stuff]
* link:llvm-games[LLVM games]
* link:tools[some tools]


== Games
Games should not be understood literally... instead these are finger exercises for the (embedded) software developer.

The following exercises are targeted:

=== Setup / Tooling
. setup xref:setup-eclipse[Eclipse], xref:setup-cmake[cmake] 
  and xref:setup-clang[clang/gcc]
. gitlab-runner
. libraries
.. STL
.. Boost

=== Unittesting
. GoogleTest [link:cpp/unittest[subdir]]
.. introduction with a simple example
.. mocking
. test driven development with a simple bag module

=== Design Patterns
. https://en.wikipedia.org/wiki/Software_design_pattern[Software Design Pattern]
.. Creational
... https://en.wikipedia.org/wiki/Builder_pattern[Builder]
... https://en.wikipedia.org/wiki/Singleton_pattern[Singleton]...
.... https://www.heise.de/blog/Patterns-in-der-Softwareentwicklung-Die-Alternativen-zum-Singleton-Muster-7280137.html[and it's alternatives]
... https://en.wikipedia.org/wiki/Factory_method_pattern[Factory]    
.. Structural
... https://en.wikipedia.org/wiki/Adapter_pattern[Adapter]
... https://en.wikipedia.org/wiki/Composite_pattern[Composite]
... https://en.wikipedia.org/wiki/Facade_pattern[Facade]
... https://en.wikipedia.org/wiki/Proxy_pattern[Proxy]
.. Behavioral
... https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern[Chain of Responsibility]
... https://en.wikipedia.org/wiki/Observer_pattern[Observer]
. https://www.heise.de/suche/?q="Patterns+in+der+Softwareentwicklung"&sort_by=date[Patterns at heise.de] and then read bottom-up
. https://en.wikibooks.org/wiki/C%2B%2B_Programming/Code/Design_Patterns[C++ Programming: Code patterns design (Wikibooks)]...
.. and the corresponding https://en.wikibooks.org/wiki/C%2B%2B_Programming[C++ Programming] book

=== LLVM
Several topics concerning link:llvm-games[LLVM].


== Self Training
There are plenty of websites for doing some self training.  My personal favourites:

* https://www.hackerrank.com[HackerRank]


[[setup-eclipse]]
== Setup

=== C/C++

==== Eclipse
For C/C++ experiments, https://eclipse.org[Eclipse] is used as IDE.
For installation details refer to https://clue.endress.com/x/mDtzBg[Clue].


[[setup-cmake]]
[[setup-clang]]
==== MSYS2
Toolchain etc is taken from https://www.msys2.org/[MSYS2].
Because my software is most of the time running on 32bit targets, MINGW32 packets are used for playing and testing
(`sizeof(void *)==4` on MINGW32, while 8 on MINGW64).

More information on MSYS2 installation can be found in https://clue.endress.com/x/SetHD[Clue].

TIP: MSYS2 installation should go to the default location `c:\msys64` to make everything work smoothly.

.Installation
[source, bash]
----
# tooling
pacman -S --needed make
pacman -S --needed mingw-w64-i686-cmake mingw-w64-i686-ninja

# gcc
pacman -S --needed mingw-w64-i686-gcc mingw-w64-i686-gdb

# clang
pacman -S --needed mingw-w64-i686-clang mingw-w64-i686-compiler-rt mingw-w64-i686-lldb mingw-w64-i686-clang-analyzer mingw-w64-i686-clang-tools-extra
----


==== Visual Studio Code
As an alternative https://code.visualstudio.com/[VSC] can be used.  Not my real favorite, because every addition or change to it's setup ends in >1h googling.
But flexibility is great and there exists a load of extensions.
The following is just a loose collection of topics concerning VSC.

===== .vscode/settings.json

.Adding MINGW32 to the Terminal Setup
[source, json]
----
    "terminal.integrated.profiles.windows": {
        "MINGW32": {
            "path": "C:\\msys64\\usr\\bin\\bash.exe",
            "args": [
                "--login",
                "-i"
            ],
            "env": {
                "MSYSTEM": "MINGW32",
                "CHERE_INVOKING": "1"
            }
        },
    },
    "terminal.integrated.defaultProfile.windows": "MINGW32",
----

==== Linux
Setup for running the tests/everything under Linux should be quite simple: under
Debian install `gcc-multiarch` and `g++-multiarch` to get 32bit applications
(sometimes the tests need to be generated with `-m32`).

NOTE: Compiling with clang is most of the times much faster: the fielddevice
unittests need 60s with gcc on my machine, while it took 15s with clang.
Most of clangs advantage comes from better usage of multiple cores.  Don't
know, what the actual cause is, that gcc behaves "bad".



