:imagesdir: doc
:source-highlighter: rouge
:toc:
:toclevels: 5


## Const and Variables

Sometimes one wonder, where variables or constants are actually placed.
The test program in link:main.c[main.c] does some examples with
corresponding output.

To determine placement correctly, the test program is executed in the target.
Output is obtained via RTT.

Minimum linker and startup code were also created.

WARNING: The startup code and linker files cannot be considered generic.
Instead they are optimized for simplicity for this use case.
So transfer them to your own projects with extreme care.



### Startup Code and Linker Script

Difficulty of this example was to get it compile with gcc and clang including
minimum infrastructure containing link instructions, linker script and
startup code.  Additional effort was to keep all those files
as small as possible to make it more clear, what actually happens.

Two cases:

gcc & newlib::
   This is often the standard for bare metal development because this
   configuration is often available thru regular package installation. +
   `crt` of newlib leaves a lot of work to be done by the startup code.

clang & picolib::
   This is my personal favorite, see the link:../../tools/build-llvm[how to build].
   `crt` of picolib seems to do a lot more of the startup action so that
   the target dependent startup code can be kept simpler. +
   There is a https://github.com/picolibc/picolibc/blob/main/picolibc.ld.in[linker script template] in the picolib sources which
   is nicely commented.

Different options can be selected via the make targets `cmake-create-{debug|release}-{gcc|clang}`.


### Links

* https://www.codeinsideout.com/blog/stm32/compilation/[Compilation process with Linker and Startup code]
* https://embeddedartistry.com/blog/2019/04/17/exploring-startup-implementations-newlib-arm/[Exploring Startup Implementations: Newlib (ARM)]
