:source-highlighter: highlight.js
:toc:
:toclevels: 4

== C/C++ Playground

=== Subdirectories
* link:games/README.adoc[games] - playing around with stuff
* link:unittest/README.adoc[unittest] (sort of)
* link:design-pattern/README.adoc[design pattern]
* link:modules[modules] - contains some modules required for playing
* link:cmake[cmake] - contains some macros (at the moment one) for cmake


=== Makefile
The link:Makefile[Makefile] is required for seamless Eclipse integration.
Because the Makefile can be called from mixed cygwin/MSYS2 environments, every line
and the order of lines in the Makefile are counting.
Essential part is the correct setup of the `PATH` environment variable.
This assures that the MSYS2 toolchain is really used before anything else in the `$PATH`.

TIP: `c:/msys64/usr/bin/make.exe` should be used as the
"Build command" in "Project Settings/C++ Build" in Eclipse.

NOTE: fun fact: internally we will let cmake use Ninja because it is faster
and shows less problems compared to make.

NOTE: this setup is working under Linux as well.


=== CMakeLists.txt
This is the root link:CMakeLists.txt[CMakeLists.txt] file.  All other `CMakeLists.txt`
are included with an invocation of `add_subdirectory()`.
Unittests are included through the cmake macro `add_unittest()`.

TIP: `add_unittest()` is not limited to unittesting.  It allows
quick and dirty inclusion of small test projects as well.
