== Boilerplate for Generic Cortex-M Experiments

=== Links
* https://mcuoneclipse.com/2022/09/04/tutorial-creating-bare-bare-embedded-projects-with-cmake-with-eclipse-included/


=== Example Project
Output counter via semihosting.  The program must run within gdb and
semihosting of OpenOCD has to be enabled.

nRF52840 is used as the target.  Only target dependency is within the
linker file.

Compiler ist clang from 
https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm[LLVM-embedded-toolchain-for-Arm]. 



=== Configuration
Minor configuration takes place in `Makefile`.


=== Debugging
For best debugging result, OpenOCD from PlatformIO should be used.  The original
OpenOCD (0.12) has some issues with the dual cores of the RP2040.

Debug configuration in Eclipse thus uses on my machine the OpenOCD path
`~/.platformio/packages/tool-openocd-rp2040-earlephilhower/bin/openocd`
and `-s ~/.platformio/packages/tool-openocd-rp2040-earlephilhower/share/openocd/scripts -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 8000"`
in the configuration options.

Semihosting must be enabled for the example to work.

[NOTE]
====
Output speed is perhaps not as expected, actually low speed.
====
